### ISSUE TITLE
Emotion 10

### ISSUE THREAD

**Issue by mitchellhamilton** [emotion-js/emotion#637]
Emotion 10 is going to introduce some new APIs for React users.

The main aim with these new APIs is to move all insertion to inside the React tree, this enables a couple of things:

* SSR just works because we can render style elements directly into the React tree.
* Setting things like nonces, container elements and stylis plugins is much easier since it only requires a Provider at the top of the tree.
* Global styles can change over time and be removed
* It forces people to think in terms of styling elements instead of creating class names
* The css prop works without the babel plugin because it's implemented as a custom `createElement` (this isn't necessarily a result of moving things inside the React tree but a side-effect of the new implementation)

The main new APIs are a custom `createElement` for the css prop and a `Global` component for global styles.

### Example

> The exact APIs are likely to change before Emotion 10 is released.

```jsx
/** @jsx jsx */
import { jsx, Global } from '@emotion/core'
import css from '@emotion/css'
import { render } from 'react-dom'

render(
  <div>
    <h1
      css={css`
        font-size: 500px;
      `}
    >
      This is really big
    </h1>
    <Global
      css={{
        body: {
          backgroundColor: 'hotpink'
        }
      }}
    />
  </div>,
  document.getElementById('root')
)
```

If you want to try this, look at https://github.com/emotion-js/next but note that there **will** be breaking changes very often for now.

Another change that emotion@10 will bring is that `styled.div` and etc. will work without a babel plugin. The tag list will be included in `@emotion/styled` but if you use `@emotion/styled.macro` with [babel-plugin-macros](https://github.com/kentcdodds/babel-plugin-macros) or the babel plugin, `styled.div` will be replaced with `styled('div')` and `@emotion/styled-base` will be imported instead which doesn't include the tag list.

## Compatibility with Preact and non-React-like libraries

While the majority of Emotion users use React, there are some users who don't use React and we have to figure out how to cater for them.

### Non-React-like libraries

Since all the packages on the `@emotion` scope are very modular, we can build the current emotion APIs with the packages on the `@emotion` scope. This should be pretty simple.

### Preact

There are only a few APIs that we use that are new.

##### Fragment

Fragments are only used for SSR so we could have an alternative SSR API for that similar to `extractCritical` now.

##### createContext

We could tell people to use `create-react-context` and essentially polyfill `createContext`.

##### forwardRef

We could conditionally use forwardRef so if it's not available then we don't use it. I'm not a huge fan of this because I think it would be confusing to tell people they should use `ref` when using React and `innerRef` when using Preact but I'm not totally sure yet.

The other option to all of this is to not support the new APIs on Preact and have Preact users use the current emotion API.

## Migration

This is something I'm still thinking about and I've got some ideas about but nothing concrete yet. I'm thinking of migrating [emotion.sh](https://emotion.sh) and seeing what's difficult, how to make incremental migration easy, what can be done automatically with codemods and what warnings would be useful to provide.

## Removing `extractStatic`

`extractStatic` hasn't been something that we've encouraged for a long time so @tkh44 and I think it's time to remove it. For people who like static extraction, libraries like [Linaria](https://linaria.now.sh/) and [css-literal-loader](https://github.com/4Catalyzer/css-literal-loader) do static extraction much better than Emotion does so those people should use those libraries.

## Only do transformations when emotion is imported

`babel-plugin-emotion` currently transforms anything with the names of emotion's exports. While this works it transforms things for other libraries (#626 and #344) so we should only transform . I want to do this in Emotion 10 since it could be a breaking change for some people.

### TODO

* [x] Support source maps in `@emotion`
* [x] Try to make the `keyframes` API more convenient
* [x] Reorganize some internals
* [x] Add a babel plugin for hoisting objects in the css prop and adding a css call around the object since we can't use a babel macro.
* [x] Add an alternative SSR API to get around the caveats with rendering style elements
* [x] Add component selectors to `@emotion/styled.macro`
* [x] Add a dev warning when `:first-child` and selectors like it are used and recommend replacements because of problems when rendering style elements in SSR and those selectors targeting the style elements.
* [x] Move https://github.com/emotion-js/next into this repo
* [x] Decide on how versioning should work since there are lots of packages that will likely have breaking changes that don't affect most end-users so should we do major versions really often(probably not) or do independent versioning for each package and if so should we start at 1.0.0 or 10.0.0?
* [x] docs. docs. docs.
* [x] Add a deprecation notice for `extractStatic` in babel-plugin-emotion and add a notice to the docs (if anyone wants to submit a PR for this, that would be great!!)
* [x] Remove `extractStatic`
* [x] probably more stuff
* [x] Make it so the new snapshot serializer doesn't mutate the object that's passed in

**Comment by mitchellhamilton** [comment]
The main downside is that it'll be hard to get class names outside of render if you're using the new APIs, that's intentional though. Another smaller thing that I haven't really figured out yet is `keyframes`, currently in the new API, you use it like this
```jsx
/** @jsx jsx */
import jsx from '@emotion/jsx'
import keyframes from '@emotion/keyframes'
import css from '@emotion/css'

const animation = keyframes(css`
  from {
    color: green;
  }
  to {
    color: hotpink;
  }
`)

const Comp = () => (
  <div
    css={[
      {
        animation: `1s ${animation.name}`
      },
      animation.styles
    ]}
  />
)
```
which is pretty inconvenient since you have to pass in the name and the styles, for string styles we could interpolate the animation object and insert the animation but for object styles we can't do that since we only have a string when we interpolate the object. Any thoughts on how we could solve this?

**Comment by Andarist** [comment]
> Another change that emotion@10 will bring is that styled.div and etc. will work without a babel plugin. The tag list will be included in @emotion/styled but if you use @emotion/styled.macro, styled.div will be replaced with styled('div') and @emotion/styled-base will be imported instead which doesn't include the tag list.

What is the argument behind this? IMHO it brings unnecessary config right from the start when one wants to use `emotion` in production (assuming everyone should do it as it's less bytes without the tag list).

> We could conditionally use forwardRef so if it's not available then we don't use it. I'm not a huge fan of this because I think it would be confusing to tell people they should use ref when using React and innerRef when using Preact but I'm not totally sure yet.

IMHO consistency is better, so I'd vote for keeping `innerRef`. In the meantime it might be good to research what preact's plans are about those new React APIs.

> extractStatic hasn't been something that we've encouraged for a long time so @tkh44 and I think it's time to remove it. For people who like static extraction, libraries like Linaria and css-literal-loader do static extraction much better than Emotion does so those people should use those libraries.

Even if the feature is not actively developed and in non-ideal state, I don't quite see why should it be removed. It surely has some audience, brings some benefits to the users and having it might encourage outside contributors to make it cover more cases.

**Comment by mitchellhamilton** [comment]
> >  Another change that emotion@10 will bring is that styled.div and etc. will work without a babel plugin. The tag list will be included in but if you use .macro, styled.div will be replaced with styled('div') and will be imported instead which doesn't include the tag list.
>
>What is the argument behind this? IMHO it brings unnecessary config right from the start when one wants to use emotion in production (assuming everyone should do it as it's less bytes without the tag list).

I'm not sure if you're referring to using a babel macro or including the tag list by default so I'll talk about both
- I added the tag list to make the API more consistent between using the babel plugin and not using it so that the only differences between using the babel plugin and not using it are performance/size optimizations and DX improvements
- In terms of doing the optimization with a babel macro, it was mainly because macros will be supported in react-scripts@2 and because the API made the optimization really easy. I think it would be a good idea to do it with a babel plugin as well. What I'd like to do though is make a util that accepts a certain import source and a function that transforms it with the same API as a babel macro so we can reuse all the logic and we don't have problems like #344 and #626 

 > > extractStatic hasn't been something that we've encouraged for a long time so @tkh44 and I think it's time to remove it. For people who like static extraction, libraries like Linaria and css-literal-loader do static extraction much better than Emotion does so those people should use those libraries.
>
> Even if the feature is not actively developed and in non-ideal state, I don't quite see why should it be removed. It surely has some audience, brings some benefits to the users and having it might encourage outside contributors to make it cover more cases.

It requires some runtime code for styled so removing it would mean styled would be slightly smaller. (I know the amount of code it uses isn't very big, it still helps though) While extractStatic may have some small audience, other libraries do a better job of it so there's no reason people should use emotion over those other libraries. Also, explaining it in the docs is hard because we have to essentially say "we have this thing, it doesn't work very well, we don't recommend it and we're not planning on improving it but it's still here".

If we did keep it and contributors improved it, it would still likely require you to follow certain rules to make it statically analyzable which would limit the power of css-in-js.

**Comment by Andarist** [comment]
> If we did keep it and contributors improved it, it would still likely require you to follow certain rules to make it statically analyzable which would limit the power of css-in-js.

That is true, `emotion`'s (and other css-in-js) true power lies in dynamic per props & theme styling, but at the same time not everything is dynamic in styles and that static part can be extracted. Keeping it would allow perfecting algorithm some day and would combine benefits of static extraction & dynamic styling at the same time. Just my 2 cents though 😉

**Comment by greggb** [comment]
Really excited about the direction of this. Had a couple of questions while thinking about what I might need to update.

If the css prop will be the favored approach do you envision most components having a bunch of outer scope variables for these styles? I really enjoy the css prop pattern, but it messes with the readability of a complexly styled components. This will somewhat involve class naming for the variables. e.g.

```
const borderedBox = css`<styles>`;

const Box = props => <div css={borderedBox} ...<lots of props>><a bunch of nested components></div>
```
>Another change that emotion@10 will bring is that styled.div and etc. will work without a babel plugin. The tag list will be included in @emotion/styled but if you use @emotion/styled.macro, styled.div will be replaced with styled('div') and @emotion/styled-base will be imported instead which doesn't include the tag list.

Does this means for optimal perf we'll need to use `styled('div')` or 
```
if(isProd) {
import(@emotion/styled.macro)
} else {
import(@emotion/styled)
}
styled.div
```

>The css prop works without the babel plugin because it's implemented as a custom createElement

Does this mean doubling the number of dom elements or is it just a React implementation of the element?

**Comment by mitchellhamilton** [comment]
> If the css prop will be the favored approach do you envision most components having a bunch of outer scope variables for these styles? I really enjoy the css prop pattern, but it messes with the readability of a complexly styled components. This will somewhat involve class naming for the variables. e.g.

Could you give an example of what you would write now for that case?

> Does this means for optimal perf we'll need to use styled('div') or

It only means you'll always be able to use `styled.div`. If you use `@emotion/styled` without the babel plugin, you'll include the tag list. If you use `@emotion/styled.macro` which requires [babel-plugin-macros](https://github.com/kentcdodds/babel-plugin-macros) which will be included in create-react-app 2 or you use the babel plugin, `styled.div` will be converted to `styled('div')` and `@emotion/styled-base` will be imported which doesn't include the tag list.

> Does this mean doubling the number of dom elements or is it just a React implementation of the element?

I'm not sure if I totally understand what you mean but the only time when there will be more dom elements is when doing SSR and style elements get rendered. You can look at how it works [here](https://github.com/emotion-js/next/blob/master/packages/core/src/jsx.js)

**Comment by greggb** [comment]
Here's a meaty one:
```
const primaryStyle = css`
    background: ${colorMap.GreenDark};
    border: 1px solid ${colorMap.GreenDark};
    color: #fff;
    font-size: ${size.default};
    &:hover {
        background: #507b32;
        border-color: ${colorMap.GreenDark};
        color: #fff;
    }
    &:active {
        ${primaryActiveStyle};
    }
    &[disabled],
    &[disabled]:hover {
        background-color: ${colorMap.slateNeutral};
        border: 1px solid #e9ebec;
        box-shadow: -2px 4px 2px -4px ${colorMap.slateLight};
        color: ${colorMap.slateLight};
    }
`;
```

> It only means you'll always be able to use styled.div.

Ok, so nothing changes if we're using the babel plugin already. 👍 My concern was that it would be more performant in dev to use the whitelist, but fewer bytes over the wire with the macro (hence a different import depending on env.)

> I'm not sure if I totally understand what you mean but the only time when there will be more dom elements is when doing SSR
> Add a dev warning when :first-child and selectors like it are used and recommend replacements because of problems when rendering style elements in SSR and those selectors targeting the style elements.

Cool, then this won't affect my project atm, but my concern was adding another dom node for every css prop used on the page. For large pages I'd imagine this could add overhead. 

Losing `:first-child` is going to be a little confusing for some of my junior devs when we start server-rending. I wonder if the babel plugin could change `:first-child` to `:first-of-type` or `first-child:not(<customElement class>)`?

**Comment by greggb** [comment]
Most of the examples and docs so far use inline styles for the css prop. It seems like the goal is to move toward that and away from `styled`. If that's not true than nothing is really different, I was thinking of new users who would be writing long strings of styles within a component and not knowing there are alternatives.

I thought this might work `$('div :first-child:not(style)')`, but realized you can't actually select `style` 🤦‍♂️

**Comment by mitchellhamilton** [comment]
@andywer Just to be clear, we're not patching createElement, we're providing a function that you explicitly use instead of createElement.

IMO, creating a custom reconciler would be so much more complex, require a lot of work(and maintenance over time since it would have to be changed every time that react-dom was changed) and wouldn't really have any significant advantages over a custom createElement.

Also, having a custom reconciler would make it harder to share components since you would have to make people use the custom reconciler as well rather than just exporting a component and using it with react-dom. This is especially important because one of the goals with this was to make it possible to create components with styles that can just be imported from npm and just work without any configuration including server-side rendering.

**Comment by hedgepigdaniel** [comment]
> Add an alternative SSR API to get around the caveats with rendering style elements

Can you point me in the direction of what you mean by this?

I've done some experimenting with https://github.com/emotion-js/next and its worked an absolute treat. Feels really clean/simple, and as you said, SSR just works since the style tags come out as part of the standard rendered react component tree.

One good argument in favour of using things like the `extractStatic` option or Linaria (i.e. extracting style information into css files) is that it avoids the needs to send style information twice on the initial render (Once before/in the server rendered HTML to ensure that the page renders correctly the first time, and once again as part of the javascript so that it can continue to keep the styles up to date after React mounts). With `https://github.com/faceyspacey/extract-css-chunks-webpack-plugin` and associated packages you can avoid that duplication as long as you put the styles into CSS files somewhere in your build pipeline.

Is that something that is or could be addressed with this new approach of rendering style tags within react? This has got me thinking though - already with SSR you duplicate the HTML (the SSR HTML version and the javascript/React version). I guess this is just an extension of that.

**Comment by mitchellhamilton** [comment]
@hedgepigdaniel The caveat I'm referring to is that `:first-child` and pseudo classes like it are unsafe because the style elements are rendered next to other elements so the pseudo classes could target the style elements instead of the element they're intended to be targeting.

The new approach doesn't change anything with regards to static extraction. I'm not very interested in static extraction right now, I personally find the trade offs not worth the benefits. I think that the only practical way to do static extraction without big trade offs is with something like prepack.

**Comment by hedgepigdaniel** [comment]
Ah cool. Since the box is checked... where is the alternative SSR API?

If I do `ReactDom.renderToString(<App />)` with the latest `@emotion/core`, the style tags are throughout the DOM tree in the rendered HTML, not in `<head />. It sounds like this new approach is a way of SSRing the app such that the styles are all in the `<head />`.

**Comment by mitchellhamilton** [comment]
@hedgepigdaniel the alternative api is using the current emotion ssr apis with the compat cache. 

You can see an example of it in the tests, 
https://github.com/emotion-js/emotion/blob/master/next-packages/compat-cache/__tests__/server.js

**Comment by FezVrasta** [comment]
How's going to work the custom `createElement` with CRA?

Do they support the `/** @jsx jsx */` comment and we are going to use it on every single file, or there is some way to change that setting globally?

**Comment by Andarist** [comment]
I highly doubt they disallow jsx pragma, so it should "just work" with the mentioned `/** @jsx jsx */` comment. If you want to change it globally you'd have to use smth like creat-react-app-rewired.

**Comment by Ailrun** [comment]
Is there a way to disable pragma with `babel-plugin-transform-react-jsx`? As far as I know, there is no such way...

**Comment by lifeiscontent** [comment]
anyone know if innerRef has been converted to ref in this branch? It's the only thing that is stopping me from using emotion.

**Comment by mitchellhamilton** [comment]
Yes, using ref is supported in v10.

**Comment by lifeiscontent** [comment]
@mitchellhamilton any idea on when v10 might be released?

**Comment by mitchellhamilton** [comment]
It’s in beta, you can see the docs at https://next.emotion.sh

**Comment by lifeiscontent** [comment]
@mitchellhamilton can I install the beta with `yarn add emotion@next`?

**Comment by mitchellhamilton** [comment]
Read the instructions at https://next.emotion.sh/docs/migrating-to-emotion-10, all packages not on the emotion npm scope + the react native packages are available on the next tag on npm, all the new packages are on the latest tag.

**Comment by lifeiscontent** [comment]
@mitchellhamilton I'm looking for an API that works similar to this.


base/Button.js

``` jsx
const Button = ({
  as,
  pressed,
  className,
  disabledClassName,
  pressedClassName,
  ...props
}) =>
  React.createElement(as, {
    className: cx(className, {
      [disabledClassName]: props.disabled,
      [pressedClassName]: pressed,
    }),
    'aria-pressed': pressed,
    'aria-disabled': props.disabled,
    ...props,
  });

Button.defaultProps = {
  as: 'button',
  className: 'Button',
  disabledClassName: 'Button--is-disabled',
  pressedClassName: 'Button--is-pressed',
};

Button.propTypes = {
  as: PropTypes.oneOfType([PropTypes.node, PropTypes.func]),
  className: PropTypes.string,
  disabled: PropTypes.bool,
  disabledClassName: PropTypes.string,
  pressed: PropTypes.bool,
  pressedClassName: PropTypes.string,
};

export { Buton };

```

theme/Button.js

``` jsx
import { Button as BaseButton } from "../base/Button";

const Button = styled(Button)(props => ({className: css(...), pressedClassName: css(...)}));

export { Button };
```

do you have a recommended way on how to achieve something like this in emotion 10?

**Comment by ConAntonakos** [comment]
@mitchellhamilton Awesome changes! Really looking forward to v10. Is it still intended to include a `<ScopeProvider/>` to help with CSS prioritization and interoperability with other styling techniques/libraries? I see that there is a module called `@emotion/provider` from the docs. Thank you!

**Comment by lifeiscontent** [comment]
@mitchellhamilton I found <ClassNames> but it looks like its not properly passing the theme that is injected from the ThemeProvider.

**Comment by mitchellhamilton** [comment]
> @mitchellhamilton Awesome changes! Really looking forward to v10. Is it still intended to include a <ScopeProvider/> to help with CSS prioritization and interoperability with other styling techniques/libraries? I see that there is a module called @emotion/provider from the docs. Thank you!

We're not planning on including something like ScopeProvider natively but it's possible to build it based on the CodeSandbox I showed. Where did you see `@emotion/provider` in the docs? It shouldn't be used.

> @mitchellhamilton I found <ClassNames> but it looks like its not properly passing the theme that is injected from the ThemeProvider.

Are you using the `ThemeProvider` from `emotion-theming@next`

**Comment by ConAntonakos** [comment]
> We're not planning on including something like ScopeProvider natively but it's possible to build it based on the CodeSandbox I showed. Where did you see @emotion/provider in the docs? It shouldn't be used.

Ok, got it. Thanks for the clarification. In order to work with other styling libraries or deal with CSS prioritization, are the traditional methods the best route forward? For example, wrapping an already externally styled component like so `styled(ComponentWithJSS)` or do you recommend something like the `<ScopeProvider />`?

Looks like you caught the import mistake: https://github.com/emotion-js/emotion/commit/56581cbb56c4e3386211c740719dfe40095141b9#diff-12703cf35278a283eae498a16e376670. Thanks for updating.

**Comment by mitchellhamilton** [comment]
> In order to work with other styling libraries or deal with CSS prioritization, are the traditional methods the best route forward? For example, wrapping an already externally styled component like so styled(ComponentWithJSS) or do you recommend something like the <ScopeProvider />?

if `styled(ComponentWithJSS)` works, keep using it.

**Comment by lifeiscontent** [comment]
@mitchellhamilton good point, I'll check on that and report back 👍

**Comment by lifeiscontent** [comment]
@mitchellhamilton how would you test a component with a theme using the ClassNames component?

**Comment by lifeiscontent** [comment]
just wrap each component with a provider?

**Comment by mitchellhamilton** [comment]
Yes, wrap it in a ThemeProvider.

**Comment by jgoux** [comment]
Hi @mitchellhamilton , I'm giving emotion 10 a try today and I have a few questions : 
- Is it planned to add automatic insertion of `/** @jsx jsx */` with `babel-plugin-emotion`? (I saw the mention `Alternatively, use this TODO babel preset` in the migration guide)

- Is `ClassNames` necessary for passing a className to a component? If we use `babel-plugin-emotion`, is it possible to use this syntax instead
```js
const activeClassName = css` color: blue;`
```

- What's the exact purpose of the exported `css` from `@emotion/core`? Is there any access to the props when using `css` ?

So far it seems promising! ⭐️

**Comment by mitchellhamilton** [comment]
> Is it planned to add automatic insertion of /** @jsx jsx */ with babel-plugin-emotion? (I saw the mention Alternatively, use this TODO babel preset in the migration guide)

You can use eslint-plugin-emotion which will add it.

> Is ClassNames necessary for passing a className to a component?

In general, you should use the css prop, ClassNames should rarely if ever be used.

> If we use babel-plugin-emotion, is it possible to use this syntax instead

No.

> What's the exact purpose of the exported css from @emotion/core?

Syntax highlighting, performance, allowing interpolations, you pass the result of the `css` to the css prop.

>  Is there any access to the props when using css?

No.

**Comment by jgoux** [comment]
> You can use eslint-plugin-emotion which will add it.
I was more looking for a compile step than a codemod. Ideally I'd like the pragma to be absent from my code.

> In general, you should use the css prop, ClassNames should rarely if ever be used.
My use case is the `activeClassName` prop from react-router `Link` component. I don't really understand why a render-prop is necessary to get the className with `css`.

Thanks for your answers! 👍

**Comment by ncknuna** [comment]
I have a similar need to regularly pass a className to a component from a third party library (in my case, Ant Design, https://ant.design/, which many of my UI components wrap and add additional styles to). I can make the ClassNames render-prop work, but having a lighter-weight solution would be nice...

**Comment by mitchellhamilton** [comment]
> My use case is the activeClassName prop from react-router Link component. I don't really understand why a render-prop is necessary to get the className with css.

It's necessary to allow the out of the box server rendering and to access context so things like iframes and providing options can work via context


With adding the pragma globally, I don't really understand why people find it so important? It takes two lines to import and set the pragma and for that, it makes it easier for people who may not have used emotion or the css prop to understand why the css prop gets converted into a className since they can see that the jsx pragma has changed, look at emotion from that and etc.

**Comment by jgoux** [comment]
> It's necessary to allow the out of the box server rendering and to access context so things like iframes and providing options can work via context

Ok, I can live with it. Thanks again for explaining me the tradeoffs. 👍 

> With adding the pragma globally, I don't really understand why people find it so important? It takes two lines to import and set the pragma

As a developer I'm lazy and if I can automate a thing and type less then I always go that road. We should at least have the possibility to do it even if it's not officially advertised.

> it makes it easier for people who may not have used emotion or the css prop to understand why the css prop gets converted into a className since they can see that the jsx pragma has changed, look at emotion from that and etc.

With the current ecosystem and the heavy usage of compilers such as Babel, I find it more understandable to rely on a plugin to transform my code globally (when the plugins usage are well explained). It also reduce the technical noise in my codebases, every line not written is a win, especially when these lines are about implementation details and can be automated.

This is all my own opinion of course! 😇

**Comment by mitchellhamilton** [comment]
> We should at least have the possibility to do it even if it's not officially advertised.

Yep, I agree, and it's totally possible, you can use the babel plugin you mentioned, [the emotion site even uses a similar plugin](https://github.com/emotion-js/emotion/blob/master/site/plugins/gatsby-plugin-emotion-next-compat/gatsby-node.js). We may even create a babel preset to do that but the one thing that I'm afraid of is that I don't want to create too many choices for people when they want to use emotion so if we add babel preset it likely won't be the primary way we intend for people to use it since importing it and setting the jsx pragma works everywhere whereas adding a preset only works when you have access to the babel config.

**Comment by jgoux** [comment]
For now I gave a possible userland solution [here](https://github.com/facebook/create-react-app/issues/5152#issuecomment-432808543) for anyone interested.

Thanks for the answer @mitchellhamilton , and amazing job on emotion 10! 👏

**Comment by Andarist** [comment]
@jgoux https://github.com/emotion-js/emotion/pull/917

**Comment by Emiliano-Bucci** [comment]
Hi to all, i'm encountering some issues using the new version of Emotion with next.js and typescript. The fact is that every time i use 
`/** @jsx jsx */
import { jsx } from "@emotion/core";`
i always have the same error:  ReferenceError: jsx is not defined
I've tried to made a fresh install (without typescript) and works fine, so maybe is an issue with typescript? Or a babel next.js config? Does anyone had the same problem?
Thanks a lot :)

**Comment by Kovensky** [comment]
https://github.com/babel/babel/issues/8958

**Comment by Emiliano-Bucci** [comment]
@Kovensky Sorry but, what do you mean by 

> Adding an unused jsx reference anywhere to the file makes the build correct

**Comment by Kovensky** [comment]
You can literally just write a random `jsx;` statement anywhere. Linters hate it!

But it works...

**Comment by Emiliano-Bucci** [comment]
That's odd but yes, it works! Thanks a lot :)

**Comment by tkh44** [comment]
@Emiliano-Bucci, have you tried setting the jsx pragma in your babel config?

**Comment by lifeiscontent** [comment]
@mitchellhamilton in emotion 10, how would you handle the case where you have a base button and a theme button? https://gist.github.com/lifeiscontent/0c025a2fcb36cc9dc0848054411649c7

I'm really unsure what the refactor would look like here for theme button.

**Comment by mitchellhamilton** [comment]
@lifeiscontent https://gist.github.com/mitchellhamilton/af7cd8e25aac4bb3ed0871c1a6003223

**Comment by lifeiscontent** [comment]
@mitchellhamilton thanks a lot. Sorry, just 1 more question in the BaseButton, there is an option to have a disabledClassName prop, how would you forward that if it was created in this case?

**Comment by mitchellhamilton** [comment]
I would probably use a child selector and target `[disabled]` and `[aria-pressed]` instead of the class names.

**Comment by lifeiscontent** [comment]
@mitchellhamilton so with this refactor it looks like I can't use the component as a selector somewhere else.

e.g. `css({[Button]: {...someStyle}});`

**Comment by FezVrasta** [comment]
```js
css`
  ${Button} {
    color: red;
  }
`
```

is how it works with template literals, I'm not sure about object notation

**Comment by lifeiscontent** [comment]
@FezVrasta it doesn't work with either in this case, probably due to something special that happens when you wrap a component using styled.div, etc.

**Comment by lifeiscontent** [comment]
@mitchellhamilton how would you use `useContext` with a `styled(Button)`?

**Comment by JesseChrestler** [comment]
@mitchellhamilton does css in Emotion 10 become the same as a styled component at render time. From what i can see in the react tab it appears to be the case, can you confirm?

**Comment by mitchellhamilton** [comment]
> does css in Emotion 10 become the same as a styled component at render time. From what i can see in the react tab it appears to be the case, can you confirm?

What do you mean by `become the same as a styled component at render time`?. They have different implementations if that's what you're asking.

> how would you use useContext with a styled(Button)?

After hooks are stable and #967 is in, you'll be able to use hooks like useContext inside of interpolations.

**Comment by JesseChrestler** [comment]
@mitchellhamilton would
Example1: `const MyRedBox = <div css={css({backgroundColor:'red'})}></div>`
be the same as
Example2: `const MyRedBox = styled.div({backgroundColor:'red'})`
I know the styles are obviously the same. From what i could tell it seemed like `Example1` was wrapping itself around the <div> tag that it was assigned to. This must be part of the babel transforms that rewrite the output. This changes a lot of things and the expectation around the component and how they are being used. Maybe I'm wrong so i'm just trying to verify my thoughts. Thanks.

**Comment by mitchellhamilton** [comment]
It's wrapping the output but the examples are different, the first one is creating an element, the second is creating a component.

> This changes a lot of things and the expectation around the component and how they are being used.

such as?

**Comment by JesseChrestler** [comment]
> such as?
The css prop becomes _magical_ higher order components that are attaching to the ref of your element to add a class name. It seems like a lot of work just to add a class name. Is this so css will work with react-native, and other devices that don't support style sheets? What are the advantages to this approach (vs v9)

**Comment by mitchellhamilton** [comment]
> magical

Using magical to describe something is very unhelpful because it doesn’t really describe what’s wrong with something. Anything could be described as magical.



> attaching to the ref of your element

We don’t use refs at all, refs are forwarded to the inner element.

> What are the advantages to this approach (vs v9)

- The css prop is a first-class citizen, not some hacky thing that breaks easily in certain cases + it works without the Babel plugin(especially great for create react app and codesandbox)
  - While this seems like a small thing, it completely changed how i use emotion, you don't have to think about classes or components, you have the smallest primitive in react, an element, and you can apply styles to it
- Passing options like nonces, container elements, etc. via a Provider
  - this makes emotion much easier to use with iframes(while this seems like a small use, I think it could be really useful, for example, Netlify CMS shows previews in iframes) and if people want, web components 
- Zero configuration SSR, you don’t have to configure SSR at all, use react’s renderToString or renderToNodeStream and nothing else
  - The streaming performance will also be much better than the old implementation, this will be especially important when suspense SSR is out since a LOT more people will be doing streaming 
  - This is especially great for component libraries since consumers don’t need to know about emotion to do ssr

Also, something that’s important to note, we’re not getting of the old APIs, if you want to keep using them, you still can, you just won’t get the advantages of the new APIs.

**Comment by lifeiscontent** [comment]
@mitchellhamilton looks like there was an option to set displayName in the babel plugin for emotion, how would you achieve the same thing in emotion@10? Is the babel plugin still required?

**Comment by mitchellhamilton** [comment]
Yes, the babel plugin is still required for labels(except with the css prop with function components). It's enabled by default in the v10 babel plugin.

**Comment by joshuakelly** [comment]
Does this work with react-native and are there any performance concerns?

**Comment by slikts** [comment]
> You can literally just write a random jsx; statement anywhere in the file. Linters hate it!

Is there a workaround to having to add `jsx`? I'm using CRA with TS and the `@jsx` pragma and the unused `jsx` statement make for a pretty ugly look. I suppose it's related to: https://github.com/babel/babel/issues/8958

**Comment by jgoux** [comment]
@slikts For CRA v1 you can use https://github.com/timarney/react-app-rewired to extend the config without ejecting. For the v2 there is https://github.com/sharegate/craco which I use and it works great! 👍
I'm not using TS so I'm not sure about the compatibility.

**Comment by slikts** [comment]
I added craco and babel-plugin-emotion and put this in craco.config.js:
```
module.exports = function({ env, paths }) {
  return {
    babel: {
      plugins: ["babel-plugin-emotion"],
    },
  };
};
```
```
Also:  `plugins: ["emotion"],`

Then ran `craco start`, with no effect, `--verbose` just says `craco:  Added Babel plugins.`, and removing the `jsx` statement still causes "jsx is not defined".

I suppose there were reasons for these changes, but from my perspective emotion has taken a big step down; it used to take just importing the template tag, but now I need to add 3 additional lines of noise: the babel pragma, the unused jsx import, and also an unused jsx statement.

**Comment by jgoux** [comment]
@slikts I don't think the `@emotion/babel-preset-css-prop` preset is included in `babel-plugin-emotion`.
See here : https://emotion.sh/docs/css-prop#babel-preset

**Comment by slikts** [comment]
I installed `@emotion/babel-preset-css-prop` and added `presets: ["@emotion/babel-preset-css-prop"],` to `craco.config.js`, and now it claims to have applied the presets, but the only configuration that works is still with the 4 lines.

I liked emotion because it was minimal and elegant and allowed me to write CSS instead of object literals. Now it's Babel pragmas, unused imports, incompatibility with CRA/TS, and object literals in the main examples. It should have at least been released as -beta or -rc in the current state.

**Comment by tkh44** [comment]
@slikts while I agree this takes more work, you can still use `import { css } from 'emotion'` or `import styled from '@emotion/styled'` just like you have been before. You do not have to use the css prop.

```
import styled from '@emotion/styled'

const Button = styled.button`
  color: turquoise;
`
```

**Comment by slikts** [comment]
I didn't say they're unsupported, just that the examples in the readme and elsewhere used to use template literals. It would be just:
```js
import { css } from "emotion";

render(<div className={css`
  color: red;
`} />, root);
```
This was what I found elegant and why I used emotion; using CSS syntax, and having a clear model that, for example, you wouldn't have to explain to a colleague if they read your code. In contrast, the changes with pragmas and seemingly unused imports are hacky and fiddly. They're using a feature of Babel that I can't even find where it's documented, and I had to piece together what it is from a random blog post. The emotion readme just drops it there as if you'd be supposed to be familiar with it. Then, to actually use CSS syntax, I have to add an another import. I basically wouldn't even try to sell the new pattern to someone else who's possibly skeptical of CSS-in-JS as such, because it doesn't look good, requires an explanation, and even with an explanation it's like magic.

**Comment by tkh44** [comment]
> This was what I found elegant and why I used emotion; using CSS syntax, and having a clear model that, for example, you wouldn't have to explain to a colleague if they read your code.

Your example still works. 

> In contrast, the changes with pragmas and seemingly unused imports are hacky and fiddly. They're using a feature of Babel that I can't even find where it's documented, and I had to piece together what it is from a random blog post. The emotion readme just drops it there as if you'd be supposed to be familiar with it.

While it needs to be better documented, you do not have to use the css prop if you don't want it. https://emotion.sh/docs/css-prop is the only page in the documentation that shows object styles before string styles simply because that is what I prefer to use and it does not require and additional import. In order to use emotion you've always had to import the `css` function just as you showed in your example. Using objects with the `css` prop allows you to write styles without imports.

**Comment by slikts** [comment]
> Your example still works.

It doesn't, the `css` tag function returns an object, and I'd have to know to use the vanilla package, which anyone familiarizing themselves with the library would probably miss and just see the css prop and Babel pragmas. The very first example in the readme also uses object literals.

**Comment by akullpp** [comment]
> I basically wouldn't even try to sell the new pattern to someone else who's possibly skeptical of CSS-in-JS as such, because it doesn't look good, requires an explanation, and even with an explanation it's like magic.

This is a real issue, it is unacceptable to use the pragma as it seems hacky compared to styled-components. I won't  introduce emotion because of this issue in a project...

**Comment by Andarist** [comment]
The good thing is that no one is forcing you to do that. You also have `@emotion/styled` API for grabs if you prefer using styled-components-like API.

We just don't believe that jsx pragma is a hack - you are free to feel to think differently.

**Comment by DominicTobias** [comment]
Does emotion wrap every component in the app in a Consumer for the sake of theming? If so it would be nice to be able to disable that
